### ISSUE TITLE
Null field behavior

### ISSUE THREAD

**Issue by MarkPflug** [Open-NET-Libraries/Open.Text.CSV#1]
Hello,
I was adding your library to a [collection of benchmarks for .NET CSV parsers](https://github.com/joelverhagen/NCsvPerf/pull/38). I'm running into problems as I can't see a way to access empty fields. The field enumerator seems to skip over empty fields, and it becomes impossible to know what column the data came from. Is this the expected behavior? Is there a way to configure the parser to yield empty strings or null in such cases?

**Comment by electricessence** [comment]
Interesting, if it's a blank field, it should end up blank... aka two commas.

**Comment by electricessence** [comment]
Lemme look.

**Comment by electricessence** [comment]
I think I see the issue.  Because I'm using a regex, it might skip blank entries.
https://github.com/Open-NET-Libraries/Open.Text.CSV/blob/master/CsvUtility.cs#L19

I'll see if I can revise.

**Comment by electricessence** [comment]
I appreciate the comparison, although I don't think I'm doing anything special that would produce competitive performance.

**Comment by electricessence** [comment]
Working on fix.  Will publish shortly.

**Comment by electricessence** [comment]
Version 2.3.3 released with fix.

**Comment by MarkPflug** [comment]
Thanks, that fixed it. If you'd rather not have your library included in the benchmarks, I can remove it from the PR. I was just adding a handful of libraries that I'd found searching nuget.

**Comment by electricessence** [comment]
I don't mind it in your benchmarks. :)  I just expect it to be at the bottom.  :)

**Comment by MarkPflug** [comment]
https://www.joelverhagen.com/blog/2020/12/fastest-net-csv-parsers
You aren't at the bottom. In fact, you're faster than two of the Microsoft-owned libraries.

**Comment by electricessence** [comment]
@MarkPflug This is super cool!  Thanks for including me.
There are improvements I could make for perf and memory.  You might wanna see if you can profile memory use too.
For now, it's great to know what's best.

**Comment by electricessence** [comment]
BTW, I haven't checked, but are your 1 million file CSV tests including long quoted strings?

**Comment by MarkPflug** [comment]
This benchmark set isn't something that I put together, I'm just a participant. My library, Sylvan.Data.Csv, is one of the libraries being tested. The benchmark project was authored by @joelverhagen. A number of people, including myself, have added additional libraries to the project.

> are your 1 million file CSV tests including long quoted strings?

No, there are no quoted fields in this particular CSV benchmark.

**Comment by electricessence** [comment]
Very cool.  Thanks for the info.

**Comment by electricessence** [comment]
@MarkPflug BTW... Congrats on your perf!

**Comment by electricessence** [comment]
Made an update.   Async methods.  Curious if you get better perf from those.  There's a cheat in there that might improve a 1M line stream read. :)

**Comment by electricessence** [comment]
@MarkPflug ok so you made me go and do it.  Regexes were not robust or performant enough so I rewrote the `CsvReader` completely and implemented a state machine mostly based on the HomeGrown source linked in the article.
Added more tests, and I'm a lot happier with the implementation.  Simpler, more robust, and likely more performant.
Thanks for stirring the pot!

**Comment by MarkPflug** [comment]
I compared 2.4.0 and 3.0.0, it dropped from 14.59s to 5.30s when running Joel's benchmarks. Huge Improvement! Nice work @electricessence!

**Comment by electricessence** [comment]
😄
